# Generated by Django 4.2.7 on 2025-08-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_tree', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('explaining', '説明フェーズ'), ('questioning', '質問フェーズ'), ('completed', '完了'), ('paused', '一時停止')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knowledge_tree.knowledgenode', verbose_name='現在のノード')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_tree.learningmaterial', verbose_name='学習教材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'インタビューセッション',
                'verbose_name_plural': 'インタビューセッション',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='質問内容')),
                ('question_type', models.CharField(choices=[('clarification', '明確化'), ('elaboration', '詳細化'), ('application', '応用'), ('connection', '関連性'), ('evaluation', '評価')], max_length=20, verbose_name='質問タイプ')),
                ('depth_level', models.IntegerField(default=1, verbose_name='深掘りレベル')),
                ('context_chunks', models.JSONField(default=list, verbose_name='コンテキストチャンク')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_tree.knowledgenode', verbose_name='対象ノード')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_session.interviewsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': '質問',
                'verbose_name_plural': '質問',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTimeoutTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('timeout_seconds', models.IntegerField(default=300, verbose_name='タイムアウト秒数')),
                ('is_active', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interview_session.question', verbose_name='現在の質問')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeout_timer', to='interview_session.interviewsession', verbose_name='セッション')),
            ],
            options={
                'verbose_name': 'タイムアウトタイマー',
                'verbose_name_plural': 'タイムアウトタイマー',
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='説明内容')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='explanations/', verbose_name='音声ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='interview_session.interviewsession', verbose_name='セッション')),
                ('topics_mentioned', models.ManyToManyField(related_name='mentioned_in_explanations', to='knowledge_tree.knowledgenode', verbose_name='言及されたトピック')),
            ],
            options={
                'verbose_name': '説明',
                'verbose_name_plural': '説明',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回答内容')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='answers/', verbose_name='音声ファイル')),
                ('understanding_score', models.FloatField(default=0.0, verbose_name='理解度スコア')),
                ('needs_deeper_questioning', models.BooleanField(default=False, verbose_name='さらなる深掘りが必要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='interview_session.question', verbose_name='質問')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答',
                'ordering': ['-created_at'],
            },
        ),
    ]
