# Generated by Django 4.2.7 on 2025-08-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0003_alter_documentchunk_learning_material'),
        ('interview_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_tree.knowledgenode', verbose_name='対象ノード'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('understanding', '理解確認'), ('clarification', '明確化'), ('elaboration', '詳細化'), ('application', '応用'), ('connection', '関連性'), ('evaluation', '評価'), ('follow_up', 'フォローアップ')], max_length=20, verbose_name='質問タイプ'),
        ),
    ]
