# Generated by Django 4.2.7 on 2025-08-20 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.TextField(verbose_name='説明')),
                ('level', models.IntegerField(default=0, verbose_name='階層レベル')),
                ('order', models.IntegerField(default=0, verbose_name='順序')),
                ('understanding_score', models.FloatField(default=0.0, verbose_name='理解度スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge_tree.knowledgenode', verbose_name='親ノード')),
            ],
            options={
                'verbose_name': '知識ノード',
                'verbose_name_plural': '知識ノード',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('file_path', models.FileField(upload_to='materials/', verbose_name='ファイル')),
                ('processed', models.BooleanField(default=False, verbose_name='処理済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_node', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='knowledge_tree.knowledgenode', verbose_name='ルートノード')),
            ],
            options={
                'verbose_name': '学習教材',
                'verbose_name_plural': '学習教材',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('embedding', models.JSONField(verbose_name='埋め込みベクトル')),
                ('page_number', models.IntegerField(verbose_name='ページ番号')),
                ('chunk_index', models.IntegerField(verbose_name='チャンクインデックス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_nodes', models.ManyToManyField(related_name='chunks', to='knowledge_tree.knowledgenode', verbose_name='関連知識ノード')),
            ],
            options={
                'verbose_name': '文書チャンク',
                'verbose_name_plural': '文書チャンク',
                'ordering': ['page_number', 'chunk_index'],
            },
        ),
    ]
