# Generated by Django 4.2.7 on 2025-08-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='learning_material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='knowledge_tree.learningmaterial'),
            preserve_default=False,
        ),
    ]
