# Generated by Django 4.2.7 on 2025-08-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0002_documentchunk_learning_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='learning_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_tree.learningmaterial', verbose_name='学習教材'),
        ),
    ]
