# Generated by Django 4.2.7 on 2025-12-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0003_alter_documentchunk_learning_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentchunk',
            options={'ordering': ['-learning_material_id', 'page_number'], 'verbose_name': '文書チャンク', 'verbose_name_plural': '文書チャンク'},
        ),
        migrations.RemoveField(
            model_name='documentchunk',
            name='chunk_index',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='learning_material',
            field=models.ForeignKey(db_column='教材ID', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge_tree.learningmaterial', verbose_name='学習教材'),
        ),
        migrations.AlterField(
            model_name='knowledgenode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='ノード名'),
        ),
    ]
