# Generated by Django 4.2.7 on 2025-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0005_alter_documentchunk_learning_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='knowledge_nodes',
        ),
        migrations.RemoveField(
            model_name='knowledgenode',
            name='understanding_score',
        ),
        migrations.AddField(
            model_name='knowledgenode',
            name='related_chunks',
            field=models.ManyToManyField(blank=True, related_name='knowledge_nodes', to='knowledge_tree.documentchunk', verbose_name='関連チャンク'),
        ),
    ]
