# Generated by Django 4.2.7 on 2025-12-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_tree', '0006_remove_documentchunk_knowledge_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='チャンクID'),
        ),
    ]
